# Generated by Django 3.2.7 on 2021-09-04 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventsd_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='formanswer',
            unique_together={('attendee', 'question')},
        ),
    ]
