- name: Setup /etc/hosts
  copy:
    content: |
      127.0.0.1 localhost

      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts

      {% for svr in groups.hypervisors %}
      {{hostvars[svr]['node_mesh_ip']}}  {{svr}}
      {% endfor %}
      {{hostvars['localhost']['primary_node_ip']}}  sf-primary
    dest: /etc/hosts
    owner: root
    group: root
    mode: u=r,g=r,o=r

- name: Determine network node
  set_fact:
    network_node_name: "{{groups.network_node[0]}}"
    network_node_ip: "{{hostvars[groups.network_node[0]]['node_mesh_ip']}}"
  delegate_to: localhost
  delegate_facts: true
  run_once: true

- name: Determine primary node
  set_fact:
    primary_node_ip: "{{hostvars['localhost']['node_egress_ip']}}"
  delegate_to: localhost
  delegate_facts: true
  run_once: true

- name: Log network and primary node
  debug:
    msg:
      - "Primary node IP is {{hostvars['localhost']['primary_node_ip']}}"
      - "Network node is {{hostvars['localhost']['network_node_name']}} with mesh IP {{hostvars['localhost']['network_node_ip']}}"
  run_once: true
