[tool.poetry]
name = "coloredconsole"
version = "0.0.2"
description = "Easy to use console coloring tool."
authors = ["Andrew Bordis <andrewbordis@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
