[tool.poetry]
name = "dataclass-applicative"
version = "0.1.0"
description = ""
authors = ["Patrick Steele <steele.pat@gmail.com>"]
maintainers = ["Patrick Steele <steele.pat@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
documentation = "https://dataclass-applicative.readthedocs.io/en/latest/"
repository = "https://github.com/prsteele/dataclass-applicative"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
hypothesis = "^6.19.0"
sphinx = "^4.1.2"
numpydoc = "^1.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
