
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-09T20:30:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cfc53d17689e1a7f24aef6fda4fd95a950d3906",
 "version": "4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
