[tool.poetry]
name = "RashSetup"
version = "0.6.2"
description = "Setup Module that can be used for both testing Rash and also Setting up Rash"
authors = ["Rahul <saihanumarahul66@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6,<3.10"
Scrapy = "^2.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
