
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-13T18:32:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "98fe1d56250e1295884489b5aa80bc3374c69314",
 "version": "2021.9.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
