# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from proto.google.fhir.proto.r4.core.datatypes_pb2 import (
    Base64Binary as proto___google___fhir___proto___r4___core___datatypes_pb2___Base64Binary,
    Boolean as proto___google___fhir___proto___r4___core___datatypes_pb2___Boolean,
    Canonical as proto___google___fhir___proto___r4___core___datatypes_pb2___Canonical,
    Code as proto___google___fhir___proto___r4___core___datatypes_pb2___Code,
    Date as proto___google___fhir___proto___r4___core___datatypes_pb2___Date,
    DateTime as proto___google___fhir___proto___r4___core___datatypes_pb2___DateTime,
    Decimal as proto___google___fhir___proto___r4___core___datatypes_pb2___Decimal,
    Id as proto___google___fhir___proto___r4___core___datatypes_pb2___Id,
    Instant as proto___google___fhir___proto___r4___core___datatypes_pb2___Instant,
    Integer as proto___google___fhir___proto___r4___core___datatypes_pb2___Integer,
    Markdown as proto___google___fhir___proto___r4___core___datatypes_pb2___Markdown,
    Oid as proto___google___fhir___proto___r4___core___datatypes_pb2___Oid,
    PositiveInt as proto___google___fhir___proto___r4___core___datatypes_pb2___PositiveInt,
    Reference as proto___google___fhir___proto___r4___core___datatypes_pb2___Reference,
    String as proto___google___fhir___proto___r4___core___datatypes_pb2___String,
    Time as proto___google___fhir___proto___r4___core___datatypes_pb2___Time,
    UnsignedInt as proto___google___fhir___proto___r4___core___datatypes_pb2___UnsignedInt,
    Uri as proto___google___fhir___proto___r4___core___datatypes_pb2___Uri,
    Url as proto___google___fhir___proto___r4___core___datatypes_pb2___Url,
    Uuid as proto___google___fhir___proto___r4___core___datatypes_pb2___Uuid,
    Xhtml as proto___google___fhir___proto___r4___core___datatypes_pb2___Xhtml,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class PrimitiveProtoUnion(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def base64_binary(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Base64Binary: ...

    @property
    def boolean(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Boolean: ...

    @property
    def canonical(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Canonical: ...

    @property
    def code(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Code: ...

    @property
    def date(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Date: ...

    @property
    def date_time(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___DateTime: ...

    @property
    def decimal(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Decimal: ...

    @property
    def id(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Id: ...

    @property
    def instant(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Instant: ...

    @property
    def integer(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Integer: ...

    @property
    def markdown(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Markdown: ...

    @property
    def oid(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Oid: ...

    @property
    def positive_int(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___PositiveInt: ...

    @property
    def string_proto(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___String: ...

    @property
    def time(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Time: ...

    @property
    def unsigned_int(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___UnsignedInt: ...

    @property
    def uri(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Uri: ...

    @property
    def url(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Url: ...

    @property
    def uuid(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Uuid: ...

    @property
    def xhtml(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Xhtml: ...

    @property
    def reference(self) -> proto___google___fhir___proto___r4___core___datatypes_pb2___Reference: ...

    def __init__(self,
        *,
        base64_binary : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Base64Binary] = None,
        boolean : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Boolean] = None,
        canonical : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Canonical] = None,
        code : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Code] = None,
        date : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Date] = None,
        date_time : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___DateTime] = None,
        decimal : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Decimal] = None,
        id : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Id] = None,
        instant : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Instant] = None,
        integer : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Integer] = None,
        markdown : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Markdown] = None,
        oid : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Oid] = None,
        positive_int : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___PositiveInt] = None,
        string_proto : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___String] = None,
        time : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Time] = None,
        unsigned_int : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___UnsignedInt] = None,
        uri : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Uri] = None,
        url : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Url] = None,
        uuid : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Uuid] = None,
        xhtml : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Xhtml] = None,
        reference : typing___Optional[proto___google___fhir___proto___r4___core___datatypes_pb2___Reference] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"base64_binary",b"base64_binary",u"boolean",b"boolean",u"canonical",b"canonical",u"code",b"code",u"date",b"date",u"date_time",b"date_time",u"decimal",b"decimal",u"id",b"id",u"instant",b"instant",u"integer",b"integer",u"markdown",b"markdown",u"oid",b"oid",u"positive_int",b"positive_int",u"primitive_proto_oneof",b"primitive_proto_oneof",u"reference",b"reference",u"string_proto",b"string_proto",u"time",b"time",u"unsigned_int",b"unsigned_int",u"uri",b"uri",u"url",b"url",u"uuid",b"uuid",u"xhtml",b"xhtml"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"base64_binary",b"base64_binary",u"boolean",b"boolean",u"canonical",b"canonical",u"code",b"code",u"date",b"date",u"date_time",b"date_time",u"decimal",b"decimal",u"id",b"id",u"instant",b"instant",u"integer",b"integer",u"markdown",b"markdown",u"oid",b"oid",u"positive_int",b"positive_int",u"primitive_proto_oneof",b"primitive_proto_oneof",u"reference",b"reference",u"string_proto",b"string_proto",u"time",b"time",u"unsigned_int",b"unsigned_int",u"uri",b"uri",u"url",b"url",u"uuid",b"uuid",u"xhtml",b"xhtml"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"primitive_proto_oneof",b"primitive_proto_oneof"]) -> typing_extensions___Literal["base64_binary","boolean","canonical","code","date","date_time","decimal","id","instant","integer","markdown","oid","positive_int","string_proto","time","unsigned_int","uri","url","uuid","xhtml","reference"]: ...
type___PrimitiveProtoUnion = PrimitiveProtoUnion

class ValidPair(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    json_string: typing___Text = ...

    @property
    def proto(self) -> type___PrimitiveProtoUnion: ...

    def __init__(self,
        *,
        json_string : typing___Optional[typing___Text] = None,
        proto : typing___Optional[type___PrimitiveProtoUnion] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"proto",b"proto"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"json_string",b"json_string",u"proto",b"proto"]) -> None: ...
type___ValidPair = ValidPair

class PrimitiveTestSuite(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    invalid_json: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
    no_invalid_protos_reason: typing___Text = ...

    @property
    def valid_pairs(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ValidPair]: ...

    @property
    def invalid_protos(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PrimitiveProtoUnion]: ...

    def __init__(self,
        *,
        valid_pairs : typing___Optional[typing___Iterable[type___ValidPair]] = None,
        invalid_json : typing___Optional[typing___Iterable[typing___Text]] = None,
        invalid_protos : typing___Optional[typing___Iterable[type___PrimitiveProtoUnion]] = None,
        no_invalid_protos_reason : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"invalid_json",b"invalid_json",u"invalid_protos",b"invalid_protos",u"no_invalid_protos_reason",b"no_invalid_protos_reason",u"valid_pairs",b"valid_pairs"]) -> None: ...
type___PrimitiveTestSuite = PrimitiveTestSuite
