
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-08T21:41:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "474deb1cb132e28b0696a9e2146545ec5de2b2e8",
 "version": "2.4.0dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
