
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-31T10:50:09-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b87e3dec9f2abea957c845602b1cb80707dfd8a5",
 "version": "1.86.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
