
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-14T22:39:18+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "3f0ae374e42cb97aae21271bf0bfdd9e5e6a7e0b",
 "version": "3.7.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
