
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-09T17:07:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7693cea996ab2704fed99593b34f5b258faea277",
 "version": "1.6.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
