
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-09T14:27:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5e82c48e8ee5af352f2c9b1690050f4e02fc1b6",
 "version": "0.7.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
