[tool.poetry]
name = "pylic"
version = "1.2.6"
description = "Python license checker"
authors = ["Sandro Huber <sandrochuber@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.9"
toml = "^0.10.2"
importlib-metadata = "^4.6.4"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
flake8 = "^3.9.2"
mypy = "^0.910"
setuptools = "^57.4.0"
wheel = "^0.37.0"
twine = "^3.4.2"
taskipy = "^1.8.1"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
isort = "^5.9.3"
types-toml = "^0.1.5"

[tool.taskipy.tasks]
release = "scripts/create_new_release.sh"
publish_docker = "scripts/publish_new_docker.sh"
test = "pytest --cov=./ --cov-report=xml"
quality = "black . && flake8 --count . && isort . && mypy ."

[tool.pylic]
safe_licenses = [
    "Public Domain",
    "BSD License",
    "Apache Software License",
    "Apache License 2.0",
    "MIT License",
    "Python Software Foundation License",
    "Mozilla Public License 2.0 (MPL 2.0)",
    "GNU Library or Lesser General Public License (LGPL)",
]

[tool.black]
line_length = 120

[tool.isort]
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
line_length = 120

[tool.coverage.run]
omit = ["setup.py", "pylic/__main__.py", "tests/*"]

[tool.coverage.report]
exclude_lines = [
    "if __name__ == .__main__.:",
    "from importlib_metadata import Distribution, distributions", # tested by integration tests
]

[tool.mypy]
files = ["pylic", "tests"]
namespace_packages = true
explicit_package_bases = true
disallow_any_unimported = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
