
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-10T16:21:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d976f5b4daa5cd9129ed1a936bd7ccc8bbe9c4e9",
 "version": "2021.09.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
