[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "go_to_github"
author = "Kate Wang"
author-email = "kate.wang2018@gmail.com"
home-page = "https://github.com/KateWang2016/go_to_github"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"

