[tool.poetry]
name = "code_census"
version = "0.0.3"
description = "A command line tool to collect, organize, report code metrics."
authors = ["Kracekumar <me@kracekumar.com>"]
license = "MIT"
include = ["alembic.ini"]
packages = [
         {include = "alembic"}
]

[tool.poetry.dependencies]
python = "^3.9"
click = "tortoise-orm[asyncpg]"
SQLAlchemy = "1.4.0"
alembic = "^1.6.5"
psycopg2 = "^2.9.1"
SQLAlchemy-Utils = "^0.37.8"
rich = "^10.7.0"
mypy = "^0.910"
beautifulsoup4 = "^4.9.3"
lxml = "^4.6.3"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
mypy = "^0.910"
taskipy = "^1.8.1"
mkdocs = "^1.2.2"
mkdocs-material = "^7.2.6"
mkdocs-click = "^0.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
mypy_report = "mypy --config-file=pyproject.toml . --html-report ."
docs_serve = "mkdocs serve"
docs_build = "mkdocs build"

[tool.poetry.scripts]
census = "code_census.cli:cli"
code_census = "code_census.cli:cli"

