
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-09T11:42:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe82e0c8afbe5278a9424f9b0eeabc921df274a4",
 "version": "0.7.1.post.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
