#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['filelock']

extras_require = \
{'test': ['pytest', 'flake8', 'flake8-bugbear'],
 "test:implementation_name=='cpython'": ['black', 'mypy', 'types-filelock']}

entry_points = \
{'console_scripts': ['condor-git-config = condor_git_config:main']}

setup(name='condor_git_config',
      version='0.1.3',
      description='dynamically configure an HTCondor node from a git repository',
      author=None,
      author_email='Max Fischer <maxfischer2781@gmail.com>',
      url=None,
      py_modules=['condor_git_config'],
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
