
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-09T10:20:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad2658709da7145a07abd0ad1078b6e7485a9939",
 "version": "4.5.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
