[tool.poetry]
name = "d_py"
version = "0.0.3"
description = "helper package for discord.py processes"
authors = ["Andrew Bordis <andrewbordis111@gmail.com>", "Ryan Cundiff <ryantcundiff@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "^1.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
