name: pynhd-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # async_retriever deps
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - nest-asyncio
  - ujson

  # pygeoogc deps
  - defusedxml
  - owslib
  - pydantic
  - pyyaml
  - pyproj
  - requests
  - requests-cache
  - shapely
  - urllib3

  # pygeoutils deps
  - affine
  - dask
  - geopandas
  - netcdf4
  - numpy
  - rasterio
  - xarray

  # pynhd deps
  - networkx
  - pandas
  - pyarrow

  # deps to speed up xarray and geopandas
  - pygeos
  - bottleneck

  # test deps
  - pre-commit
  - psutil
  - pytest
  - pytest-clarity
  - pytest-cov
  - pytest-sugar
  - pytest-xdist

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
