
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T23:37:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f399352467118511a364a8ec4502f809933c6bce",
 "version": "5.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
