
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-10T13:26:15-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a5ff66d01f2801f02dac44d5f17ca2c93b6fa4f",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
