# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: akkaserverless/component.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='akkaserverless/component.proto',
  package='akkaserverless',
  syntax='proto3',
  serialized_options=b'\n\022com.akkaserverlessB\016ComponentProtoP\001ZHgithub.com/lightbend/akkaserverless-go-sdk/akkaserverless;akkaserverless',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x61kkaserverless/component.proto\x12\x0e\x61kkaserverless\"V\n\x12\x45ventSourcedEntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0e\n\x06\x65vents\x18\x04 \x03(\t\"?\n\x0bValueEntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\tBp\n\x12\x63om.akkaserverlessB\x0e\x43omponentProtoP\x01ZHgithub.com/lightbend/akkaserverless-go-sdk/akkaserverless;akkaserverlessb\x06proto3'
)




_EVENTSOURCEDENTITY = _descriptor.Descriptor(
  name='EventSourcedEntity',
  full_name='akkaserverless.EventSourcedEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='akkaserverless.EventSourcedEntity.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='akkaserverless.EventSourcedEntity.entity_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='akkaserverless.EventSourcedEntity.state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='akkaserverless.EventSourcedEntity.events', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=136,
)


_VALUEENTITY = _descriptor.Descriptor(
  name='ValueEntity',
  full_name='akkaserverless.ValueEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='akkaserverless.ValueEntity.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='akkaserverless.ValueEntity.entity_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='akkaserverless.ValueEntity.state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['EventSourcedEntity'] = _EVENTSOURCEDENTITY
DESCRIPTOR.message_types_by_name['ValueEntity'] = _VALUEENTITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventSourcedEntity = _reflection.GeneratedProtocolMessageType('EventSourcedEntity', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSOURCEDENTITY,
  '__module__' : 'akkaserverless.component_pb2'
  # @@protoc_insertion_point(class_scope:akkaserverless.EventSourcedEntity)
  })
_sym_db.RegisterMessage(EventSourcedEntity)

ValueEntity = _reflection.GeneratedProtocolMessageType('ValueEntity', (_message.Message,), {
  'DESCRIPTOR' : _VALUEENTITY,
  '__module__' : 'akkaserverless.component_pb2'
  # @@protoc_insertion_point(class_scope:akkaserverless.ValueEntity)
  })
_sym_db.RegisterMessage(ValueEntity)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
