
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-07T12:34:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "619a9294b07ed46956980ac0c40ff8198e252cf0",
 "version": "0.6.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
