
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-11T06:57:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9b02270701ac57c8b2fa4ec9ffcd13138b56ca9",
 "version": "2021.9.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
