site_name: "docutools"
site_description: "Documentation Building Tools"
site_url: "https://AXGKl.github.io/docutools"
repo_url: "https://github.com/AXGKl/docutools"
repo_name: "docutools"

# configure your own scheme handler for this, dependent on where YOU want to edit (repo server or local fs):
edit_uri: editor://$repos/docutools/docs

copyright: |
  Copyright &copy; 2021 Gunther Klessinger
#
nav:
  - Overview: index.md
  - Installation:
      - install.md
  - Features:
      - Overview: features/index.md
      - Plugins:
          - Blacklist: features/blacklist/index.md
          - Changelog: features/changelog/index.md
          - Credits: features/credits/index.md
          - Find Pages: features/find-pages/index.md
          - Literate Programming (LP):
              - Overview: features/lp/index.md
              - Syntax: features/lp/syntax.md
              - Parameters: features/lp/parameters.md

              - Evaluation and Caching: features/lp/eval.md
              - Sessions: features/lp/sessions.md
              - Terminal Colors: features/lp/xterm.md
              - Async Fetching: features/lp/async.md
              - Tips: features/lp/tips.md
              - Examples: features/lp/examples.md
          - LP Plugins:
              - Overview: features/lp/plugins.md
              - features/lp/plugins/bash.md
              - features/lp/plugins/cov_report.md
              - features/lp/plugins/mermaid.md
              - features/lp/plugins/make_badges.md
              - features/lp/plugins/make_file.md
              - features/lp/plugins/python.md
              - features/lp/plugins/show_file.md
              - features/lp/plugins/show_src.md

          - Markdown Replace: features/md-replace/index.md
          - Page Tree: features/page-tree/index.md
          - Stats: features/stats/index.md
      - Third Party: features/third.md
      - "TermCasts": features/termcasts/index.md
      - Darkmode: features/darkmode.md
  - About:
      - Coverage: about/coverage.md
      - Contributing: about/contributing.md
      - Changelog: about/changelog.md
      - Credits: about/credits.md
      - TODO: about/todo.md

theme:
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.sections
      #- navigation.expand
  name:
    material
    #custom_dir: docs/lcd
  icon:
    logo: material/book-open-page-variant
  palette:
    scheme: preference
    primary: yellow
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
    #- toc.autohide

# extra_css:
#   - theme/src/css/mkdocstrings.css

markdown_extensions:
  - admonition
  - attr_list # {: style="height: ..."}
  - footnotes # foo[^1] is ...(start with ^)
  - meta
  - markdown_include.include
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - markdown.extensions.tables
  - markdown.extensions.footnotes
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
  - toc:
      permalink: "¤"
  - pymdownx.snippets:
      base_path:
        - docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AXGKl

plugins:
  - search
  - lcd-blacklist
  - lcd-changelog
  - lcd-credits
  - lcd-find-pages
  - lcd-lp
  - lcd-md-replace
  - lcd-page-tree
  - lcd-stats
  - macros:
      j2_block_start_string: "<%{"
      j2_block_end_string: "}%>"
      j2_variable_start_string: "<{"
      j2_variable_end_string: "}>"
