VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('09')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('55')
MAJOR_VERSION = 0
MINOR_VERSION = 6
PATCH_VERSION = 202109090555
version_date = '2021/09/09 05:55'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
