
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-06T11:22:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6579a0f0bcd20b42b4da229a6ab39f1e20b2fe6",
 "version": "v1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
