# Generated by Django 3.1.7 on 2021-08-24 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0021_file_extension_validator'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('theme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_interface.theme')),
                ('wo', models.TextField()),
            ],
            bases=('admin_interface.theme',),
        ),
    ]
