# Generated by Django 3.1.7 on 2021-08-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_myadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAdmin',
        ),
    ]
