
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-14T12:43:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e9b2741977bfdf615c96ca7afdba01912079a44",
 "version": "0.7.1.post.dev38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
