
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-08T00:16:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a15b3df06f8ff3982cbf15cb4e0a4a786b437d7",
 "version": "2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
