
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-06T16:35:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8fd083476784b7dcf6fc53cfb97697f6a541f2b",
 "version": "2.1.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
