name: publish

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: self-hosted
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"

            - name: Install dependencies
              run: |
                  make deps

            - name: Publish to PyPi
              env:
                  FLIT_USERNAME: __token__
                  FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
              run: |
                  make publish