
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-06T22:00:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "26373e66fbaba04fa076aebb24ad869f41f228b9",
 "version": "6.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
