
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-06T21:37:27+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "4031e8703b01f59fc8d465491376e37dab551e93",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
