dist: xenial
language: python
sudo: required
python:
  - "3.9-dev"
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsystemd-dev
  - pip install build
script:
  - pip -m build
  - pip install .
