
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-08T12:36:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2629e4520b4003008e6e33222865da0d63294dd",
 "version": "1.3.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
