# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class OrmWorkload(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'created_dt': 'datetime',
        'edges': 'OrmWorkloadEdges',
        'endpoints': 'dict(str, object)',
        'env_vars': 'dict(str, object)',
        'exit_code': 'int',
        'final_cost': 'float',
        'id': 'int',
        'immutable_slug': 'str',
        'kernel_cluster_select_policies': 'dict(str, object)',
        'message': 'str',
        'name': 'str',
        'start_command': 'str',
        'status': 'str',
        'status_last_updated': 'datetime',
        'status_reason': 'str',
        'type': 'str',
        'updated_dt': 'datetime',
        'volume_mounts': 'dict(str, object)',
        'workload_access_token': 'int',
        'workload_created_by': 'int',
        'workload_kernel_cluster': 'int',
        'workload_kernel_cluster_node': 'int',
        'workload_kernel_image': 'int',
        'workload_kernel_resource_spec': 'int',
        'workload_organization': 'int',
        'workload_project': 'int',
        'workload_sweep': 'int'
    }

    attribute_map = {
        'created_dt': 'created_dt',
        'edges': 'edges',
        'endpoints': 'endpoints',
        'env_vars': 'env_vars',
        'exit_code': 'exit_code',
        'final_cost': 'final_cost',
        'id': 'id',
        'immutable_slug': 'immutable_slug',
        'kernel_cluster_select_policies': 'kernel_cluster_select_policies',
        'message': 'message',
        'name': 'name',
        'start_command': 'start_command',
        'status': 'status',
        'status_last_updated': 'status_last_updated',
        'status_reason': 'status_reason',
        'type': 'type',
        'updated_dt': 'updated_dt',
        'volume_mounts': 'volume_mounts',
        'workload_access_token': 'workload_access_token',
        'workload_created_by': 'workload_created_by',
        'workload_kernel_cluster': 'workload_kernel_cluster',
        'workload_kernel_cluster_node': 'workload_kernel_cluster_node',
        'workload_kernel_image': 'workload_kernel_image',
        'workload_kernel_resource_spec': 'workload_kernel_resource_spec',
        'workload_organization': 'workload_organization',
        'workload_project': 'workload_project',
        'workload_sweep': 'workload_sweep'
    }

    def __init__(self, created_dt=None, edges=None, endpoints=None, env_vars=None, exit_code=None, final_cost=None, id=None, immutable_slug=None, kernel_cluster_select_policies=None, message=None, name=None, start_command=None, status=None, status_last_updated=None, status_reason=None, type=None, updated_dt=None, volume_mounts=None, workload_access_token=None, workload_created_by=None, workload_kernel_cluster=None, workload_kernel_cluster_node=None, workload_kernel_image=None, workload_kernel_resource_spec=None, workload_organization=None, workload_project=None, workload_sweep=None, local_vars_configuration=None):  # noqa: E501
        """OrmWorkload - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._created_dt = None
        self._edges = None
        self._endpoints = None
        self._env_vars = None
        self._exit_code = None
        self._final_cost = None
        self._id = None
        self._immutable_slug = None
        self._kernel_cluster_select_policies = None
        self._message = None
        self._name = None
        self._start_command = None
        self._status = None
        self._status_last_updated = None
        self._status_reason = None
        self._type = None
        self._updated_dt = None
        self._volume_mounts = None
        self._workload_access_token = None
        self._workload_created_by = None
        self._workload_kernel_cluster = None
        self._workload_kernel_cluster_node = None
        self._workload_kernel_image = None
        self._workload_kernel_resource_spec = None
        self._workload_organization = None
        self._workload_project = None
        self._workload_sweep = None
        self.discriminator = None

        if created_dt is not None:
            self.created_dt = created_dt
        if edges is not None:
            self.edges = edges
        if endpoints is not None:
            self.endpoints = endpoints
        if env_vars is not None:
            self.env_vars = env_vars
        self.exit_code = exit_code
        self.final_cost = final_cost
        if id is not None:
            self.id = id
        if immutable_slug is not None:
            self.immutable_slug = immutable_slug
        if kernel_cluster_select_policies is not None:
            self.kernel_cluster_select_policies = kernel_cluster_select_policies
        if message is not None:
            self.message = message
        if name is not None:
            self.name = name
        if start_command is not None:
            self.start_command = start_command
        if status is not None:
            self.status = status
        if status_last_updated is not None:
            self.status_last_updated = status_last_updated
        if status_reason is not None:
            self.status_reason = status_reason
        if type is not None:
            self.type = type
        if updated_dt is not None:
            self.updated_dt = updated_dt
        if volume_mounts is not None:
            self.volume_mounts = volume_mounts
        self.workload_access_token = workload_access_token
        if workload_created_by is not None:
            self.workload_created_by = workload_created_by
        self.workload_kernel_cluster = workload_kernel_cluster
        self.workload_kernel_cluster_node = workload_kernel_cluster_node
        if workload_kernel_image is not None:
            self.workload_kernel_image = workload_kernel_image
        self.workload_kernel_resource_spec = workload_kernel_resource_spec
        if workload_organization is not None:
            self.workload_organization = workload_organization
        self.workload_project = workload_project
        self.workload_sweep = workload_sweep

    @property
    def created_dt(self):
        """Gets the created_dt of this OrmWorkload.  # noqa: E501


        :return: The created_dt of this OrmWorkload.  # noqa: E501
        :rtype: datetime
        """
        return self._created_dt

    @created_dt.setter
    def created_dt(self, created_dt):
        """Sets the created_dt of this OrmWorkload.


        :param created_dt: The created_dt of this OrmWorkload.  # noqa: E501
        :type created_dt: datetime
        """

        self._created_dt = created_dt

    @property
    def edges(self):
        """Gets the edges of this OrmWorkload.  # noqa: E501


        :return: The edges of this OrmWorkload.  # noqa: E501
        :rtype: OrmWorkloadEdges
        """
        return self._edges

    @edges.setter
    def edges(self, edges):
        """Sets the edges of this OrmWorkload.


        :param edges: The edges of this OrmWorkload.  # noqa: E501
        :type edges: OrmWorkloadEdges
        """

        self._edges = edges

    @property
    def endpoints(self):
        """Gets the endpoints of this OrmWorkload.  # noqa: E501


        :return: The endpoints of this OrmWorkload.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._endpoints

    @endpoints.setter
    def endpoints(self, endpoints):
        """Sets the endpoints of this OrmWorkload.


        :param endpoints: The endpoints of this OrmWorkload.  # noqa: E501
        :type endpoints: dict(str, object)
        """

        self._endpoints = endpoints

    @property
    def env_vars(self):
        """Gets the env_vars of this OrmWorkload.  # noqa: E501


        :return: The env_vars of this OrmWorkload.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._env_vars

    @env_vars.setter
    def env_vars(self, env_vars):
        """Sets the env_vars of this OrmWorkload.


        :param env_vars: The env_vars of this OrmWorkload.  # noqa: E501
        :type env_vars: dict(str, object)
        """

        self._env_vars = env_vars

    @property
    def exit_code(self):
        """Gets the exit_code of this OrmWorkload.  # noqa: E501


        :return: The exit_code of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._exit_code

    @exit_code.setter
    def exit_code(self, exit_code):
        """Sets the exit_code of this OrmWorkload.


        :param exit_code: The exit_code of this OrmWorkload.  # noqa: E501
        :type exit_code: int
        """

        self._exit_code = exit_code

    @property
    def final_cost(self):
        """Gets the final_cost of this OrmWorkload.  # noqa: E501


        :return: The final_cost of this OrmWorkload.  # noqa: E501
        :rtype: float
        """
        return self._final_cost

    @final_cost.setter
    def final_cost(self, final_cost):
        """Sets the final_cost of this OrmWorkload.


        :param final_cost: The final_cost of this OrmWorkload.  # noqa: E501
        :type final_cost: float
        """

        self._final_cost = final_cost

    @property
    def id(self):
        """Gets the id of this OrmWorkload.  # noqa: E501


        :return: The id of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrmWorkload.


        :param id: The id of this OrmWorkload.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def immutable_slug(self):
        """Gets the immutable_slug of this OrmWorkload.  # noqa: E501


        :return: The immutable_slug of this OrmWorkload.  # noqa: E501
        :rtype: str
        """
        return self._immutable_slug

    @immutable_slug.setter
    def immutable_slug(self, immutable_slug):
        """Sets the immutable_slug of this OrmWorkload.


        :param immutable_slug: The immutable_slug of this OrmWorkload.  # noqa: E501
        :type immutable_slug: str
        """

        self._immutable_slug = immutable_slug

    @property
    def kernel_cluster_select_policies(self):
        """Gets the kernel_cluster_select_policies of this OrmWorkload.  # noqa: E501


        :return: The kernel_cluster_select_policies of this OrmWorkload.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._kernel_cluster_select_policies

    @kernel_cluster_select_policies.setter
    def kernel_cluster_select_policies(self, kernel_cluster_select_policies):
        """Sets the kernel_cluster_select_policies of this OrmWorkload.


        :param kernel_cluster_select_policies: The kernel_cluster_select_policies of this OrmWorkload.  # noqa: E501
        :type kernel_cluster_select_policies: dict(str, object)
        """

        self._kernel_cluster_select_policies = kernel_cluster_select_policies

    @property
    def message(self):
        """Gets the message of this OrmWorkload.  # noqa: E501


        :return: The message of this OrmWorkload.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this OrmWorkload.


        :param message: The message of this OrmWorkload.  # noqa: E501
        :type message: str
        """

        self._message = message

    @property
    def name(self):
        """Gets the name of this OrmWorkload.  # noqa: E501


        :return: The name of this OrmWorkload.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrmWorkload.


        :param name: The name of this OrmWorkload.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def start_command(self):
        """Gets the start_command of this OrmWorkload.  # noqa: E501


        :return: The start_command of this OrmWorkload.  # noqa: E501
        :rtype: str
        """
        return self._start_command

    @start_command.setter
    def start_command(self, start_command):
        """Sets the start_command of this OrmWorkload.


        :param start_command: The start_command of this OrmWorkload.  # noqa: E501
        :type start_command: str
        """

        self._start_command = start_command

    @property
    def status(self):
        """Gets the status of this OrmWorkload.  # noqa: E501


        :return: The status of this OrmWorkload.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OrmWorkload.


        :param status: The status of this OrmWorkload.  # noqa: E501
        :type status: str
        """

        self._status = status

    @property
    def status_last_updated(self):
        """Gets the status_last_updated of this OrmWorkload.  # noqa: E501


        :return: The status_last_updated of this OrmWorkload.  # noqa: E501
        :rtype: datetime
        """
        return self._status_last_updated

    @status_last_updated.setter
    def status_last_updated(self, status_last_updated):
        """Sets the status_last_updated of this OrmWorkload.


        :param status_last_updated: The status_last_updated of this OrmWorkload.  # noqa: E501
        :type status_last_updated: datetime
        """

        self._status_last_updated = status_last_updated

    @property
    def status_reason(self):
        """Gets the status_reason of this OrmWorkload.  # noqa: E501


        :return: The status_reason of this OrmWorkload.  # noqa: E501
        :rtype: str
        """
        return self._status_reason

    @status_reason.setter
    def status_reason(self, status_reason):
        """Sets the status_reason of this OrmWorkload.


        :param status_reason: The status_reason of this OrmWorkload.  # noqa: E501
        :type status_reason: str
        """

        self._status_reason = status_reason

    @property
    def type(self):
        """Gets the type of this OrmWorkload.  # noqa: E501


        :return: The type of this OrmWorkload.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this OrmWorkload.


        :param type: The type of this OrmWorkload.  # noqa: E501
        :type type: str
        """

        self._type = type

    @property
    def updated_dt(self):
        """Gets the updated_dt of this OrmWorkload.  # noqa: E501


        :return: The updated_dt of this OrmWorkload.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_dt

    @updated_dt.setter
    def updated_dt(self, updated_dt):
        """Sets the updated_dt of this OrmWorkload.


        :param updated_dt: The updated_dt of this OrmWorkload.  # noqa: E501
        :type updated_dt: datetime
        """

        self._updated_dt = updated_dt

    @property
    def volume_mounts(self):
        """Gets the volume_mounts of this OrmWorkload.  # noqa: E501


        :return: The volume_mounts of this OrmWorkload.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._volume_mounts

    @volume_mounts.setter
    def volume_mounts(self, volume_mounts):
        """Sets the volume_mounts of this OrmWorkload.


        :param volume_mounts: The volume_mounts of this OrmWorkload.  # noqa: E501
        :type volume_mounts: dict(str, object)
        """

        self._volume_mounts = volume_mounts

    @property
    def workload_access_token(self):
        """Gets the workload_access_token of this OrmWorkload.  # noqa: E501


        :return: The workload_access_token of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._workload_access_token

    @workload_access_token.setter
    def workload_access_token(self, workload_access_token):
        """Sets the workload_access_token of this OrmWorkload.


        :param workload_access_token: The workload_access_token of this OrmWorkload.  # noqa: E501
        :type workload_access_token: int
        """

        self._workload_access_token = workload_access_token

    @property
    def workload_created_by(self):
        """Gets the workload_created_by of this OrmWorkload.  # noqa: E501


        :return: The workload_created_by of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._workload_created_by

    @workload_created_by.setter
    def workload_created_by(self, workload_created_by):
        """Sets the workload_created_by of this OrmWorkload.


        :param workload_created_by: The workload_created_by of this OrmWorkload.  # noqa: E501
        :type workload_created_by: int
        """

        self._workload_created_by = workload_created_by

    @property
    def workload_kernel_cluster(self):
        """Gets the workload_kernel_cluster of this OrmWorkload.  # noqa: E501


        :return: The workload_kernel_cluster of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._workload_kernel_cluster

    @workload_kernel_cluster.setter
    def workload_kernel_cluster(self, workload_kernel_cluster):
        """Sets the workload_kernel_cluster of this OrmWorkload.


        :param workload_kernel_cluster: The workload_kernel_cluster of this OrmWorkload.  # noqa: E501
        :type workload_kernel_cluster: int
        """

        self._workload_kernel_cluster = workload_kernel_cluster

    @property
    def workload_kernel_cluster_node(self):
        """Gets the workload_kernel_cluster_node of this OrmWorkload.  # noqa: E501


        :return: The workload_kernel_cluster_node of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._workload_kernel_cluster_node

    @workload_kernel_cluster_node.setter
    def workload_kernel_cluster_node(self, workload_kernel_cluster_node):
        """Sets the workload_kernel_cluster_node of this OrmWorkload.


        :param workload_kernel_cluster_node: The workload_kernel_cluster_node of this OrmWorkload.  # noqa: E501
        :type workload_kernel_cluster_node: int
        """

        self._workload_kernel_cluster_node = workload_kernel_cluster_node

    @property
    def workload_kernel_image(self):
        """Gets the workload_kernel_image of this OrmWorkload.  # noqa: E501


        :return: The workload_kernel_image of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._workload_kernel_image

    @workload_kernel_image.setter
    def workload_kernel_image(self, workload_kernel_image):
        """Sets the workload_kernel_image of this OrmWorkload.


        :param workload_kernel_image: The workload_kernel_image of this OrmWorkload.  # noqa: E501
        :type workload_kernel_image: int
        """

        self._workload_kernel_image = workload_kernel_image

    @property
    def workload_kernel_resource_spec(self):
        """Gets the workload_kernel_resource_spec of this OrmWorkload.  # noqa: E501


        :return: The workload_kernel_resource_spec of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._workload_kernel_resource_spec

    @workload_kernel_resource_spec.setter
    def workload_kernel_resource_spec(self, workload_kernel_resource_spec):
        """Sets the workload_kernel_resource_spec of this OrmWorkload.


        :param workload_kernel_resource_spec: The workload_kernel_resource_spec of this OrmWorkload.  # noqa: E501
        :type workload_kernel_resource_spec: int
        """

        self._workload_kernel_resource_spec = workload_kernel_resource_spec

    @property
    def workload_organization(self):
        """Gets the workload_organization of this OrmWorkload.  # noqa: E501


        :return: The workload_organization of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._workload_organization

    @workload_organization.setter
    def workload_organization(self, workload_organization):
        """Sets the workload_organization of this OrmWorkload.


        :param workload_organization: The workload_organization of this OrmWorkload.  # noqa: E501
        :type workload_organization: int
        """

        self._workload_organization = workload_organization

    @property
    def workload_project(self):
        """Gets the workload_project of this OrmWorkload.  # noqa: E501


        :return: The workload_project of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._workload_project

    @workload_project.setter
    def workload_project(self, workload_project):
        """Sets the workload_project of this OrmWorkload.


        :param workload_project: The workload_project of this OrmWorkload.  # noqa: E501
        :type workload_project: int
        """

        self._workload_project = workload_project

    @property
    def workload_sweep(self):
        """Gets the workload_sweep of this OrmWorkload.  # noqa: E501


        :return: The workload_sweep of this OrmWorkload.  # noqa: E501
        :rtype: int
        """
        return self._workload_sweep

    @workload_sweep.setter
    def workload_sweep(self, workload_sweep):
        """Sets the workload_sweep of this OrmWorkload.


        :param workload_sweep: The workload_sweep of this OrmWorkload.  # noqa: E501
        :type workload_sweep: int
        """

        self._workload_sweep = workload_sweep

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrmWorkload):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrmWorkload):
            return True

        return self.to_dict() != other.to_dict()
