[tool.poetry]
name = "detadict"
version = "0.1.0"
description = "Python dict with Deta backend"
authors = ["ilhomidin <itilhomidin@yandex.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ilhomidin/detadict"
keywords = ["deta", "dict"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
]

[tool.poetry.dependencies]
python = "^3.7"
deta = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
pylint = "^2.10.2"
isort = "^5.9.3"
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 79

[tool.pylint.format]
max-line-length = 79
disable = '''
    C0103
'''
