[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py39,py310

[testenv]
deps = pytest >= 6.0.0, <7
commands = pytest
"""
