
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "43b9d4ef188c9feb7717ec4a562bb678c433c1c7",
 "version": "4.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
