
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T11:30:53+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "546cf76143c8e6df034954992eb36e2233e71161",
 "version": "4.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
