branches:
  only:
    - master
environment:
  matrix:
  - platform: x86
  - platform: x64
  
build: false

skip_tags: true

install:
  - echo Installed Pythons
  - dir c:\Python*

  - ps: |
      if ($env:platform -Match "x86") 
      {
        $env:PYTHON="C:\Python38\python"
      }
      elseif ($env:platform -Match "x64") 
      {
        $env:PYTHON="C:\Python38-x64\python"
      }
  - ps: |
      Set-Content -Path "requirements.txt" -Value (get-content -Path "requirements.txt" | Select-String -Pattern 'mpi4py' -NotMatch)
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

      Remove-Item -Path PyMPDATA_tests/unit_tests/test_mpi.py
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

  - ps: |
      iex "$env:PYTHON -m pip install --upgrade pip"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      
      iex "$env:PYTHON -m pip install -r test-time-requirements.txt"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

      iex "$env:PYTHON -m pip install -e ."
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
test_script:
  - ps: |
      iex "$env:PYTHON -m pytest -We -p no:unraisableexception"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
