[tool.poetry]
name = "kombai"
version = "0.0.1a0"
description = "Terminal based structured data viewer and editor written in Python"
authors = [
    "kracekumar <me@kracekumar.com>"
]
license = "MIT"
readme = "README.md"
packages = [
    { include = "kombai", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
importlib-metadata = {version = "^4.8.1", python = "<3.8"}
pytest-cov = "^2.12.1"
SQLAlchemy = ">=1.4,<1.4.23"
textual = "^0.1.10"

[tool.poetry.dev-dependencies]
pre-commit = {version = "^2.15.0", python = ">=3.6.1"}
tox = "^3.24.3"
pytest = "^6.2.5"
coverage = {version = "^5.5", extras = ["toml"]}
twine = "^3.4.2"

[tool.black]
line-length = 88
target-python = "3.6"

[tool.isort]
profile = "black"
src_paths = ["src", "test"]
known_first_party = "kombai"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "tests",
]

[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 3.13.0
isolated_build = True
envlist = py

[testenv]
whitelist_externals = poetry
setenv =COVERAGE_FILE=.coverage/data.{envname}
commands =
    poetry install --no-root
    pytest--cov --cov-report=term {posargs}

[testenv:lint]
skip_install = True
deps =
    pre-commit
commands =
    pre-commit run --all-files {posargs}

[testenv:report]
skip_install = true
deps =
    coverage[toml]
setenv =
    COVERAGE_FILE=.coverage/data
commands =
    coverage combine
    coverage report
    coverage html

[testenv:clean]
skip_install = true
deps =
    coverage[toml]
setenv =
    COVERAGE_FILE=.coverage/data
commands = coverage erase

"""

[tool.coverage.run]
branch = true
parallel = true
data_file = ".coverage/data"
# we only care about these packages
source = [
    "kombai",
]
omit = [
    "tests/*",
]

[tool.coverage.paths]
# ensure these paths are treated as equivalents
source = [
    "src/",
    "*/site-packages"
]

[tool.coverage.report]
skip_empty = true
ignore_errors = true
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:"
]

[tool.coverage.html]
directory = ".coverage/html"

[tool.coverage.xml]
output = ".coverage/coverage.xml"

[tool.coverage.json]
output = ".coverage/coverage.json"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
