[tool.poetry]
name = "wait-for-docker"
version = "0.1.1"
description = "A simple script to wait for Docker daemon to be active."
license = "MIT"
authors = ["Goto Hayato <habita.gh@gmail.com>"]
readme = "README.md"
repository = "https://github.com/gh640/wait-for-docker"
keywords = ["docker"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
docker = "^5.0.1"
yaspin = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-mock = "^3.6.1"

[tool.poetry.scripts]
wait-for-docker = "wait_for_docker.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
