version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: {{cookiecutter.project_name}}:{{"${" }}{{cookiecutter.project_name | upper }}_VERSION:-latest{{"}"}}
    env_file:
      - .env
    environment:
      - {{cookiecutter.project_name | upper }}_HOST=0.0.0.0
      {%- if cookiecutter.db_info.name == "sqlite" %}
      - {{cookiecutter.project_name | upper }}_DB_FILE=/db_data/db.sqlite3
      {%- endif %}
    {%- if cookiecutter.db_info.name == "sqlite" %}
    volumes:
      - {{cookiecutter.project_name}}-db-data:/db_data/
    {%- endif %}

  {%- if cookiecutter.db_info.name == "postgresql" %}
  db:
    image: postgres:13.4-buster
    hostname: {{cookiecutter.project_name}}-db
    environment:
      - POSTGRES_PASSWORD={{cookiecutter.project_name}}
      - POSTGRES_USER={{cookiecutter.project_name}}
      - POSTGRES_DB={{cookiecutter.project_name}}
    volumes:
      - {{cookiecutter.project_name}}-db-data:/var/lib/postgresql/data
  {%- endif %}

  {%- if cookiecutter.db_info.name == "mysql" %}
  db:
    image: bitnami/mysql:8.0.26
    hostname: {{cookiecutter.project_name}}-db
    environment:
      - MYSQL_PASSWORD={{cookiecutter.project_name}}
      - MYSQL_USER={{cookiecutter.project_name}}
      - MYSQL_DATABASE={{cookiecutter.project_name}}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - {{cookiecutter.project_name}}-db-data:/bitnami/mysql/data
  {%- endif %}

  {% if cookiecutter.enable_alembic == 'True' %}
  migrator:
    image: {{cookiecutter.project_name}}:{{"${" }}{{cookiecutter.project_name | upper }}_VERSION:-latest{{"}"}}
    {%- if cookiecutter.db_info.name == "sqlite" %}
    command: alembic upgrade head
    environment:
      - {{cookiecutter.project_name | upper }}_DB_FILE=/db_data/db.sqlite3
    volumes:
      - {{cookiecutter.project_name}}-db-data:/db_data/
    {%- else %}
    command: wait-for-it -t 180 {{cookiecutter.project_name}}-db:{{cookiecutter.db_info.port}} -- alembic upgrade head
    {%- endif %}
  {%- endif %}

  {%- if cookiecutter.enable_redis == "True" %}
  redis:
    image: bitnami/redis:6.2.5
    hostname: {{cookiecutter.project_name}}-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  {%- endif %}

{% if cookiecutter.db_info.name != 'none' %}
volumes:
  {{cookiecutter.project_name}}-db-data:
    name: {{cookiecutter.project_name}}-db-data
{% endif %}
