[project]
name = "Merlin"
version = "0.0.1"
description = "Create a pyproject.toml file for an existing project."
authors = [
    "Matthew Ebert <ebertmx@gmail.com>"
]
license = "Quandri"
readme = "README.md"
python = "^3.6"
homepage = "https://github.com/MartinThoma/infer_pyproject"
repository = "https://github.com/MartinThoma/infer_pyproject"
documentation = "https://github.com/MartinThoma/infer_pyproject"

keywords = ["packaging", "dependency", "Merlin", "pyproject.toml", "q_merlin"]

classifiers = [
    "Topic :: API Development"
]

# Requirements
[dependencies]
Click = "^7.0"

[dev-dependencies]
black = { version = "^21.8b0", python = "^3.6" }

[scripts]


[build-system]
requires = [
    "setuptools >= 35.0.2",
   
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target_version = ['py36']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''