# coding: utf-8

"""
    Nomad Envoy Utils

    This is the API descriptor for the EC Platform and customs utils. Developed by [Samarkand Global](https://samarkand.global), EC Platform including [Youzan](https://www.youzan.com/) Read the documentation online at [Nomad API Suite](https://api.samarkand.io/). - Install for python with `pip install nomad_envoy_utils_cli` - Install for node with `npm install nomad_envoy_utils_cli`  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from nomad_envoy_utils_cli.configuration import Configuration


class ApiResponseData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'items': 'list[str]',
        'are_all_encrypted': 'bool'
    }

    attribute_map = {
        'items': 'items',
        'are_all_encrypted': 'areAllEncrypted'
    }

    def __init__(self, items=[], are_all_encrypted=True, local_vars_configuration=None):  # noqa: E501
        """ApiResponseData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._items = None
        self._are_all_encrypted = None
        self.discriminator = None

        if items is not None:
            self.items = items
        if are_all_encrypted is not None:
            self.are_all_encrypted = are_all_encrypted

    @property
    def items(self):
        """Gets the items of this ApiResponseData.  # noqa: E501


        :return: The items of this ApiResponseData.  # noqa: E501
        :rtype: list[str]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this ApiResponseData.


        :param items: The items of this ApiResponseData.  # noqa: E501
        :type: list[str]
        """

        self._items = items

    @property
    def are_all_encrypted(self):
        """Gets the are_all_encrypted of this ApiResponseData.  # noqa: E501


        :return: The are_all_encrypted of this ApiResponseData.  # noqa: E501
        :rtype: bool
        """
        return self._are_all_encrypted

    @are_all_encrypted.setter
    def are_all_encrypted(self, are_all_encrypted):
        """Sets the are_all_encrypted of this ApiResponseData.


        :param are_all_encrypted: The are_all_encrypted of this ApiResponseData.  # noqa: E501
        :type: bool
        """

        self._are_all_encrypted = are_all_encrypted

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiResponseData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiResponseData):
            return True

        return self.to_dict() != other.to_dict()
