[tool.poetry]
authors = ["shoor <shoorday@gmail.com>"]
description = "西电相关工具和 CLI"
homepage = "https://github.com/shoorday/xdutools"
keywords = ["XDU", "Spider"]
license = "MIT"
name = "xdutools"
repository = "https://github.com/shoorday/xdutools"
version = "0.0.1-alpha.3"

[tool.poetry.dependencies]
asyncclick = { version = "^8.0.1.3", optional = true }
beautifulsoup4 = "^4.10.0"
colorama = { version = "^0.4.4", optional = true }
httpx = "^0.19.0"
pycryptodome = "^3.10.1"
python = "^3.9"

[tool.poetry.group.dev.dependencies]
flake8 = "^3.9.2"
black = { version = "^21.8-beta.0", allow-prereleases = true }
mypy = "^0.910"
isort = "^5.9.3"

[tool.poetry.extras]
all = ["asyncclick", "colorama"]
cli = ["asyncclick"]

[[tool.poetry.source]]
default = true
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.poetry.scripts]
xdu = "xdutools.cli:main"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
line-length = 88

[tool.isort]
line_length = 88
