# Generated by Django 2.2.24 on 2021-09-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_parametrizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretparametrizer',
            name='switch',
            field=models.BooleanField(default=False, verbose_name='Switch On/Off'),
        ),
    ]
