
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-10T16:22:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef52fc83a6316c4014f1066e942f14276347b06b",
 "version": "v0.9.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
