[tool.poetry]
name = "pyd-mon"
version = "0.2.0"
description = "A super small package for validating and converting MongoDB ObjectId's to Pydantic models."
readme = "README.md"
license = "MIT"
authors = ["Trevor Hodsdon"]
repository = "https://github.com/MrTj458/pyd-mon"
documentation = "https://github.com/MrTj458/pyd-mon"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8.2"
pymongo = "^3.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.9b0"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
