from enum import Enum


class SensorType(str, Enum):
	TEMPERATURE = 'TEMPERATURE'
	PRESSURE = 'PRESSURE'
	PERCENT = 'PERCENT'
	COUNT = 'COUNT'
	DISTANCE = 'DISTANCE'
	TIMESTAMP = 'TIMESTAMP'
	IDENTIFIER = 'IDENTIFIER'
	STRING = 'STRING'
	HUMIDITY = 'HUMIDITY'
	CONCENTRATION = 'CONCENTRATION'


