VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('14')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('14')
MAJOR_VERSION = 0
MINOR_VERSION = 7
PATCH_VERSION = 202109141514
version_date = '2021/09/14 15:14'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
