
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-14T10:15:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4e14c29f3bff401e6ccf932e91b8e6f754e9e5b",
 "version": "2.0.0a12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
