[build-system]
requires = [
    "setuptools >= 42",
    "wheel",
	"numpy",
	"opencv-python",
	"imutils",
	"dlib == 19.8.1",
	"pyqt5",
	"scikit-image >= 0.13.1",
	"matplotlib",
	"filterpy == 1.4.5"
]
build-backend = "setuptools.build_meta"