
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-06T14:49:50+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6948faded2cdbdad0cfd4162fbe88b54429ae486",
 "version": "1.0.7rc6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
