[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "brood"
version = "0.2.0"
description = "A flexible concurrent command runner."
readme="README.md"
license = "MIT"
homepage="https://github.com/JoshKarpel/brood"
authors = ["Josh Karpel <josh.karpel@gmail.com>"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Intended Audience :: Developers",
    "Typing :: Typed"]
include = ["py.typed"]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.9.0"
typer = "^0.3.2"
pydantic = "^1.8.2"
PyYAML = "^5.4.1"
watchdog = "^2.1.5"
identify = "^2.2.13"
rtoml = "^0.7.0"
gitignore-parser = "^0.0.8"
GitPython = "^3.1.20"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-mock = "^3.6.1"
types-PyYAML = "^5.4.8"
pre-commit = "^2.14.1"
hypothesis = "^6.17.2"
mypy = "^0.910"
pytest-cov = "^2.12.1"
alt-pytest-asyncio = "^0.5.4"

[tool.poetry.scripts]
brood = 'brood.main:app'

[tool.pytest.ini_options]
addopts = ["--strict-markers", "-Werror"]
testpaths = ["tests", "brood"]

[tool.mypy]
files = ["brood/*.py", "tests/*.py"]

pretty=true

check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
disallow_any_generics = true

warn_unused_configs = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
warn_redundant_casts = true

ignore_missing_imports = true

[tool.black]
line-length = 100
target-version = ["py36", "py37", "py38"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
line_length = 100
