
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-12T15:52:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cfa3dbe0a342b2e1697ac0a27b83cbc99ed0d63",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
