[tool.poetry]
name = "visiond"
version = "0.1.0"
description = "Algorithmic Trading Library"
authors = ["Chris Bradley <declarationcb@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
