VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('10')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('42')
MAJOR_VERSION = 0
MINOR_VERSION = 3
PATCH_VERSION = 202109101042
version_date = '2021/09/10 10:42'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
