
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-13T16:33:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "258415d2b4c754ba1eb3390e3b403072ecbaa4a3",
 "version": "0.10.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
