[tool.poetry]
name = "gilot"
version = "0.2.5"
description = "a git log visual analyzer"
readme = "README.md"
repository = "https://github.com/hirokidaichi/gilot"
authors = ["hirokidaichi <hirokidaichi@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.18.5"
pandas = "^1.0.4"
GitPython = "^3.1.3"
datetime = "^4.3"
seaborn = "^0.10.1"
argparse = "^1.4.0"
matplotlib = "^3.2.1"
python-Levenshtein = "^0.12.0"
networkx = "^2.4"
pyfpgrowth = "^1.0"
python-louvain = "^0.14"
timeout_decorator = "^0.4.1"
ipykernel = "^6.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
autopep8 = "^1.5.7"

[tool.poetry.scripts]
gilot = "gilot.app:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

