#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='boost_hist_plot',
      version='0.1',
      description='Functions to plot boost histograms.',
      author=None,
      author_email='Cyrille Praz <code.cyrraz@protonmail.com>',
      url=None,
      py_modules=['boost_hist_plot'],
     )
