[tool.poetry]
name = "textalytics-oss-adapters"
version = "0.1.0"
description = "textalytics interface implementation for popular NLP open source libraries"
authors = ["Manoj Bharadwaj <manoj@cloudcosmos.tech>"]
license = "MIT"

packages = [
    { include="textalytics_spacy", from="." },
    { include="textalytics_stanza", from="." },
]

[tool.poetry.dependencies]
python = "^3.9"
textalytics-core = "^0.1.1"
spacy = "^3.1.2"
stanza = "^1.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
path = "./venv"

[tool.poetry.scripts]
test = 'scripts:test'

