
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-12T20:18:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3233113d10167cb79bf58cf4f32ace7a6d40ec01",
 "version": "1.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
