[tool.poetry]
name = "libgaea"
version = "0.0.39"
description = "Spawner of the understory"
authors = ["Angelo Gladding <self@angelogladding.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [
    { include = "gaea" }
]

[tool.poetry.plugins."web.apps"]
gaea = "gaea.__web__:app"

[tool.poetry.scripts]
build_linux = "gaea:build_linux"
build_windows = "gaea:build_windows"
build_macos = "gaea:build_macos"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
PySide6 = "^6.1.2"
sh = "^1.14.2"
feedparser = "^6.0.8"
pendulum = "^2.1.2"
semver = "^2.13.0"
understory = "*"

[tool.poetry.dev-dependencies]
Nuitka = "^0.6.16"
black = "^21.7b0"
isort = "^5.9.2"
pep8-naming = "^0.12.0"
flake8-docstrings = "^1.6.0"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
ipython = "^7.25.0"
pytest-gevent = "^1.1.0"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
