
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-12T20:02:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9737ed5f65a957bd9ce4727d31e52492ca68dd06",
 "version": "v0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
