
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-07T09:43:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a238c33bcfbff8e8d099e0de39d5ad00bb87aeb",
 "version": "v1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
