#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['gr_lora_sdr_profiler']

package_data = \
{'': ['*'], 'gr_lora_sdr_profiler': ['bash_scripts/*', 'templates/*']}

install_requires = \
['flit_core>=2.2.0', 'coloredlogs', 'prompt_toolkit', 'pandas', 'wandb']

entry_points = \
{'console_scripts': ['gr-lora-sdr-profiler = gr_lora_sdr_profiler:main']}

setup(name='gr_lora_sdr_profiler',
      version='0.29',
      description='gr_lora_sdr_profiler',
      author='Martyn van Dijke',
      author_email='martijnvdijke600@gmail.com',
      url='https://github.com/martynvdijke/gr-lora_sdr-profiler',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
