
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-09T15:24:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "51d49f4574764d047c0e1e22942825402ef5bcd4",
 "version": "0.13.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
