[tool.poetry]
name = "algo-method-tools"
version = "0.1.1"
description = "algo-method用の環境構築用コマンドラインツール"
authors = ["yassu <yassu0320.dev@gmail.com>"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Topic :: Terminals",
    "Topic :: Utilities",
]

repository = "https://gitlab.com/yassu/algo-method-tools"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

beautifulsoup4 = "^4.10.0"
requests = "^2.26.0"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
algo-tools = 'algo_method_tools.main:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
