[tool.poetry]
name = "omniblack.moneta"
version = "0.0.4"
description = "A changelog manager for omniblack."
authors = ["Terry Patterson <Terryp@wegrok.net>"]
license = "AGPL-3.0-only"
packages = [
    { include = 'omniblack' }
]

[tool.poetry.dependencies]
python = "^3.9"
parver = "^0.3.1"
attrs = "^20.3.0"
"ruamel.yaml" = "^0.16.0"
GitPython = "^3.1.15"
anyio = "^3.0.1"
"omniblack.repo" = '^0.0.3'
more-itertools = "^8.8.0"

[tool.poetry.dev-dependencies]
bpython = "^0.21"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
