
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-10T11:43:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "249606d0837941ce29c897ec64af8b2cd50488e5",
 "version": "1.86.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
