[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = "{{cookiecutter.project_description}}"
authors = [

]
maintainers = [

]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.68.0"
uvicorn = "^0.15.0"
pydantic = {version = "^1.8.2", extras = ["dotenv"]}
yarl = "^1.6.3"
{%- if cookiecutter.db_info.name != "none" %}
SQLAlchemy = {version = "^1.4", extras = ["mypy", "asyncio"]}
{%- endif %}
{%- if cookiecutter.enable_alembic == "True" %}
alembic = "^1.6.5"
{%- endif %}
{%- if cookiecutter.db_info.name == "postgresql" %}
asyncpg = {version = "^0.24.0", extras = ["sa"]}
{%- endif %}
{%- if cookiecutter.db_info.name == "sqlite" %}
aiosqlite = "^0.17.0"
{%- endif %}
{%- if cookiecutter.db_info.name == "mysql" %}
aiomysql = "^0.0.21"
{%- endif %}
{%- if cookiecutter.enable_redis == "True" %}
aioredis = {version = "^2.0.0", extras = ["hiredis"]}
{%- endif %}

[tool.poetry.dev-dependencies]
pytest = "^6.0"
flake8 = "^3.9.2"
mypy = "^0.910"
isort = "^5.9.3"
yesqa = "^1.2.3"
pre-commit = "^2.11.0"
wemake-python-styleguide = "^0.15.3"
black = "^21.7b0"
{%- if cookiecutter.db_info.name != "none" %}
pytest-async-sqlalchemy = "^0.1.3"
{%- endif %}
autoflake = "^1.4"
{%- if cookiecutter.db_info.name != "none" %}
SQLAlchemy = {version = "^1.4", extras = ["mypy"]}
{%- endif %}
{%- if cookiecutter.enable_alembic %}
pytest-alembic = "^0.3.3"
{%- endif %}
pytest-cov = "^2.12.1"
pytest-asyncio = "^0.15.1"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
strict = true
ignore_missing_imports = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
{%- if cookiecutter.db_info.name != "none" %}
plugins = ["sqlalchemy.ext.mypy.plugin"]
{%- endif %}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
