[tool.poetry]
name = "text_alignment_tool"
version = "0.1.1"
description = "A tool for performing complex text alignment processes."
authors = ["Bronson Brown-deVost <bronsonbdevost@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
