[tool.poetry]
name = "roo"
version = "0.0.1"
description = "roo"
authors = ["Stefano Borini"]
packages = [
    { include = "roo", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
