[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "999"

[tool.ward]
path = ["tests"]
exclude = ["tests/.ipynb_checkpoints"]
capture-output = true
order = "random"
output-mode = "test-per-line"  # or 'dots-global', 'dot-module'
fail-limit = 20
progress-style = ["bar"]

[tool.pytest.ini_options]
addopts = "--doctest-modules --ignore=noxfile.py -n=auto -v --durations=5"
doctest_optionflags = 'NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL NUMBER'
testpaths = [
    "async_retriever",
]

[tool.mypy]
allow_redefinition = false
check_untyped_defs = true
ignore_errors = false
implicit_reexport = false
local_partial_types = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true

[isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = "async_retriever"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100
