[tool.poetry]
name = "pyespremclient"
version = "0.7.180440"
description = "A python module for ESPREM clients"
authors = ["Zafar Iqbal <ultrasine@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
requests = "^2.25.1"
numpy = "^1.19.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
