"""
    FXLuminaire Luxor

    API specification for FXLuminaire's Luxor lighting system.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import luxor_openapi_asyncio
from luxor_openapi_asyncio.model.group_list_rename_response import GroupListRenameResponse


class TestGroupListRenameResponse(unittest.TestCase):
    """GroupListRenameResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupListRenameResponse(self):
        """Test GroupListRenameResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupListRenameResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
