"""
    FXLuminaire Luxor

    API specification for FXLuminaire's Luxor lighting system.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import luxor_openapi_asyncio
from luxor_openapi_asyncio.api.controller_api import ControllerApi  # noqa: E501


class TestControllerApi(unittest.TestCase):
    """ControllerApi unit test stubs"""

    def setUp(self):
        self.api = ControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_controller_name(self):
        """Test case for controller_name

        Retrieve controller details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
