"""
    FXLuminaire Luxor

    API specification for FXLuminaire's Luxor lighting system.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import luxor_openapi_asyncio
from luxor_openapi_asyncio.model.theme_get_request import ThemeGetRequest


class TestThemeGetRequest(unittest.TestCase):
    """ThemeGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThemeGetRequest(self):
        """Test ThemeGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ThemeGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
