"""
    FXLuminaire Luxor

    API specification for FXLuminaire's Luxor lighting system.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import luxor_openapi_asyncio
from luxor_openapi_asyncio.api.lights_api import LightsApi  # noqa: E501


class TestLightsApi(unittest.TestCase):
    """LightsApi unit test stubs"""

    def setUp(self):
        self.api = LightsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_light(self):
        """Test case for assign_light

        Assign a light to a group  # noqa: E501
        """
        pass

    def test_extinguish_all(self):
        """Test case for extinguish_all

        Turn off all lights  # noqa: E501
        """
        pass

    def test_flash_lights(self):
        """Test case for flash_lights

        Flash all lights  # noqa: E501
        """
        pass

    def test_illuminate_all(self):
        """Test case for illuminate_all

        Turn on all lights  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
