
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-13T07:55:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "197e97c091de5bde643842de4788d7b807a7c162",
 "version": "0.0.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
