
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-10T13:23:45-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa6324127256e268ed7057547f9b50cc8fd287be",
 "version": "v0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
