[build-system]
# Cython dependency is optional, see setup.py for details.
# For the package (run-time) dependencies, see setup.cfg.
requires = ["setuptools", "wheel", "numpy", "Cython"]
build-backend = "setuptools.build_meta"