[tool.poetry]
name = "app-mqttc"
version = "0.1.2"
description = ""
authors = ["Ying Shaodong <helloysd@foxmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
importlib-metadata = {version = "^1.0", python = "<3.8"}
typer = {extras = ["all"], version = "^0.3.2"}
paho-mqtt = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_cli = true
log_level = "DEBUG"

[tool.poetry.scripts]
mqttc = "app_mqttc:app"
