
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-13T11:10:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "87c071b8cca1992df2f5a926e772fbf4e7bdf8de",
 "version": "0.7.1.post.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
