[tool.poetry]
name = "fuzzy-c-means"
version = "1.6.2"
description = ""
authors = ["Madson Dias <madsonddias@gmail.com>", "dirk <https://github.com/dirknbr>", "José Alberth <jalberth14@gmail.com>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/omadson/fuzzy-c-means"
repository = "https://github.com/omadson/fuzzy-c-means"
keywords = ["machine-learning", "data-science", "fuzzy-c-means", "clustering"]
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

packages = [
    { include = "fcmeans" }
]


[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.21.1"
tabulate = "^0.8.9"
typer = "^0.3.2"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pre-commit = "^2.13.0"
typer-cli = "^0.0.12"
matplotlib = "^3.4.3"
jupyterlab = "^3.1.9"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry.scripts]
fcm = 'fcmeans.cli:app'
