
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-14T12:34:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0a829443c31564b56f1844d8978067aa8ce632b",
 "version": "0.7.1.post.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
