
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-08T20:31:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b161796234670ce1c4894974eaeb590d35cf2a2",
 "version": "v1.1.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
