[tool.poetry]
name = "perm_banana"
version = "0.2.1"
description = "A Bitwise Permission Handler"
authors = ["TheJoeSmo <joesmo.joesmo12@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/TheJoeSmo/perm-banana"
repository = "https://github.com/TheJoeSmo/perm-banana"
keywords = ["permissions", "bitwise"]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = {version = "^21.7b0", allow-prereleases = true}
pytest = "^6.2.4"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
