
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-07T12:30:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4b7bf655eb04b9034dc569ed1d054f1b4fdf3272",
 "version": "v0.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
