# coding: utf-8

"""
    FXLuminaire Luxor

    API specification for FXLuminaire's Luxor lighting system.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from luxor_openapi_asyncio.configuration import Configuration


class Group(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'grp': 'int',
        'name': 'str',
        'inten': 'int',
        'colr': 'int'
    }

    attribute_map = {
        'grp': 'Grp',
        'name': 'Name',
        'inten': 'Inten',
        'colr': 'Colr'
    }

    def __init__(self, grp=None, name=None, inten=None, colr=None, local_vars_configuration=None):  # noqa: E501
        """Group - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._grp = None
        self._name = None
        self._inten = None
        self._colr = None
        self.discriminator = None

        if grp is not None:
            self.grp = grp
        if name is not None:
            self.name = name
        if inten is not None:
            self.inten = inten
        if colr is not None:
            self.colr = colr

    @property
    def grp(self):
        """Gets the grp of this Group.  # noqa: E501

        Group number  # noqa: E501

        :return: The grp of this Group.  # noqa: E501
        :rtype: int
        """
        return self._grp

    @grp.setter
    def grp(self, grp):
        """Sets the grp of this Group.

        Group number  # noqa: E501

        :param grp: The grp of this Group.  # noqa: E501
        :type grp: int
        """

        self._grp = grp

    @property
    def name(self):
        """Gets the name of this Group.  # noqa: E501


        :return: The name of this Group.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Group.


        :param name: The name of this Group.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def inten(self):
        """Gets the inten of this Group.  # noqa: E501

        Intensity  # noqa: E501

        :return: The inten of this Group.  # noqa: E501
        :rtype: int
        """
        return self._inten

    @inten.setter
    def inten(self, inten):
        """Sets the inten of this Group.

        Intensity  # noqa: E501

        :param inten: The inten of this Group.  # noqa: E501
        :type inten: int
        """

        self._inten = inten

    @property
    def colr(self):
        """Gets the colr of this Group.  # noqa: E501

        Color  # noqa: E501

        :return: The colr of this Group.  # noqa: E501
        :rtype: int
        """
        return self._colr

    @colr.setter
    def colr(self, colr):
        """Sets the colr of this Group.

        Color  # noqa: E501

        :param colr: The colr of this Group.  # noqa: E501
        :type colr: int
        """

        self._colr = colr

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Group):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Group):
            return True

        return self.to_dict() != other.to_dict()
