from selenium.webdriver.common.by import By

SIGN_IN_BUTTON = (By.XPATH, "//*[@class='btn btn-primary']")
CREATE_DOC_BUTTON = (By.XPATH, "//*[@id='create-doc-button']//a[@href='/app/dashboard/documents/new-document/']")
QUERY_FIELD = (By.XPATH, "//div[@class='doc-settings-field ng-scope']//input[@ng-model='document_queries[$index]']")
SHOW_FOLDERS_DROPDOWN = (By.XPATH, "//*[@ng-click='showChannelsDropdown()']")
FOLDERS_DROPDOWN = (By.XPATH, "//*[@ng-click='selectChanel(channel)']")
CREATE_NEW_FOLDER = (By.XPATH, "//li//a[@ng-click='showChannelForm()']")
FOLDER_NAME_FIELD = (By.XPATH, "//div[@class='doc-settings-field']//input[@ng-model='channel.name']")
CREATE_NEW_FOLDER_ACCEPT = (By.XPATH, "//a[@ng-click='createChannel(channel)']")
ADVANCED_SETTINGS = (By.XPATH, "//a[@ng-click='showAdvancedSettings()']")
SHOW_COUNTRIES_DROPDOWN = (By.XPATH, "//*[@ng-click='showCountryDropdown()']")
COUNTRIES_DROPDOWN = (
By.XPATH, "//*[@ng-show='countryDropdown']//*[@ng-click='selectCountry(code); showCountryDropdown();']")
SHOW_LANG_DROPDOWN = (By.XPATH, "//*[@ng-click='showLangDropdown()']")
LANG_DROPDOWN = (By.XPATH, "//*[@ng-show='langDropdown']//*[@ng-click='selectLanguage(lang)']")
CREATE_DOC_ACCEPT = (By.XPATH, "//a[@ng-click='createDocument()']")
DOC_SEARCH_RESULT = (By.XPATH, "//*[@class='document-search-results ng-scope']")
HEADERS_TAB = (By.XPATH, "//*[@ng-click=\"setSubview('headers')\"]")
ASSETS = (By.XPATH, "//*[@ng-click='expandHeader(asset)']")
TITLES = (By.XPATH, "//div[contains(@class, 'right-panel-row')]//span[@class='ng-binding']")
PARAGRAPHS = (By.XPATH, "//a[@class='ng-binding']")
PASTE_FULLS = (By.XPATH, "//a[contains(@ng-click,'pasteAsset(asset)')]")
WORD_COUNT = (By.XPATH, "//*[@id='word-count']//b")
MY_CONTENT_TAB = (By.XPATH, "//a[@id='editor-tab-1']")
INPUT_TEXT_FIELD = (By.XPATH, "//*[@id='text-body']")
FORMATS_BUTTON = (By.XPATH, "//button[@aria-label='Formats']")
HEADERS_BUTTON = (By.XPATH, "//*[(@title='Headers') and (@role='menuitem')]")
HEADER_2_BUTTON = (By.XPATH, "//*[(@title='Header 2') and (@role='menuitemcheckbox')]")
BLOCKS_BUTTON = (By.XPATH, "//*[(@title='Blocks') and (@role='menuitem')]")
PARAGRAPH_BUTTON = (By.XPATH, "//*[(@title='Paragraph') and (@role='menuitemcheckbox')]")
BACK_TO_HOME = (By.XPATH, "//i[@ui-sref='dashboard']")
REFUSE_NOTIFICATIONS = (By.ID, "pushActionRefuse")
FOLDERS = (By.XPATH, "//*[@ng-show='!selectedChannel']")
EDIT_FOLDER = (By.XPATH, "/html/body/div[1]/div[2]/div/div[1]/div[1]/div[1]/div[6]/div[2]/a")
DELETE_FOLDER = (By.XPATH, "//a[@ng-click='deleteChannel(channel)']")
DELETE_CONFIRMATION = (By.XPATH, "//a[@ng-click='confirmDeleteChannel(channelToDelete)']")
