name: package_config
display:
    en: Component Configuration
fields:
    - name: name
      required: true
      display:
          en: Name
      desc:
          en: The name of the package described by this configuration.
      type: string

    - name: type
      required: true
      display:
          en: Type
      desc:
          en: The type of package.
      type: string
      valid_values:
          - internal: lib
            display:
                en: Library
          - internal: app
            display:
                en: Application
          - internal: spa
            display:
                en: Single Page Application

    - name: template_path
      display:
          en: Template Path
      desc:
          en: >-
              A path to an html template to use for serving the resulting
              javascript bundle. If not provided no html file will be generated.
              This path will be resolved using the `require.resolve` algorithm.
              `@omniblack/vulcan` provides a default template at
              `@omniblack/vulcan/template.html`.

      type: string

    - name: public_path
      display:
          en: Public Path
      desc:
          en: The public path from which the spa will be served.
      type: string

    - name: pages_dir
      display:
          en: Pages Directory
      desc:
          en: The directory where the spa pages are kept.
      type: string

    - name: product_name
      display:
          en: Product Name
      desc:
          en: The name of the package to be displayed to users.
      type: child
      attrs:
          struct_name: meta:ui_string

    - name: output_dir
      display:
          en: Output Directory
      desc:
          en: The directory relative to the package to place build output.
      type: string
      assumed: build

    - name: environments
      display:
          en: Environments
      desc:
          en: The environments this package should be built for.
      type: string
      list: true
      valid_values:
          - browser
          - node
