[tool.poetry]
name = "python-progressbar"
version = "3.53.1"
description = "A Python Progressbar library to provide visual (yet text based) progress to long running operations."
authors = ["Rick van Hattem <Wolph@wol.ph>"]
license = "BSD"

[tool.poetry.dependencies]
python = "^2.7"
python-utils = "^2.5.6"
six = "^1.16.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
