[tool.poetry]
name          = "scienco"
version       = "1.0.1"
authors       = ["Andrew Malchuk <andrew.malchuk@yandex.ru>"]
description   = "Calculate the readability of text using one of a variety of computed indexes"
keywords      = ["python", "readability", "indexes", "score"]
repository    = "https://gitlab.com/amalchuk/scienco"
documentation = "https://amalchuk.gitlab.io/scienco"
readme        = "README.md"
license       = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
isort           = "^5.9"
mkdocs          = "^1.2"
mkdocs-material = "^7.2"
pytest          = "^6.2"
coverage        = { version = "^5.5", extras = ["toml"]}
mypy            = { version = "*", allow-prereleases = true }

[tool.coverage.run]
branch = true
source = ["scienco"]

[tool.coverage.report]
precision  = 2
skip_empty = true

[tool.isort]
force_single_line          = true
force_sort_within_sections = true
known_first_party          = ["scienco"]
known_local_folder         = ["tests"]
lexicographical            = true
line_length                = 125
single_line_exclusions     = ["typing"]

[build-system]
build-backend = "setuptools.build_meta"
requires      = ["setuptools", "wheel"]
