[tool.poetry]
name = "qlivi"
version = "0.1.0"
description = "dd"
authors = ["musangtara <musangtara@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7.1"
click = "^8.0.1"
requests = "^2.26.0"
pandas = "^1.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
