#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['zeversolarlocal']

package_data = \
{'': ['*']}

install_requires = \
['httpx']

extras_require = \
{'dev': ['pylint', 'nox', 'pytest-cov', 'coverage[toml]>=5.0.3', 'pre-commit'],
 'test': ['pytest', 'pytest-asyncio', 'pytest-mock']}

setup(name='zeversolarlocal',
      version='1.0.0',
      description='zeversolarlocal',
      author='Sander Teunissen',
      author_email=None,
      url='https://github.com/sander76/zeversolarlocal',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
