
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-07T09:44:37+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c9d3fa5766e8391104baaff6c6dee4a62e4e1f8",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
