
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-06T13:16:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f8f4f95ed21453674df569549d1a7e430d08ff8",
 "version": "2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
