
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-08T17:04:20+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a31d1f9bbd51111b4a4d01cf1df01a5b4827e85",
 "version": "0.9.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
