
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-09T01:37:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3cf4860f5302ee185e2c395109c485f7b86972c",
 "version": "0.1.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
