
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-13T19:25:32+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "57b8af1af7d5e3de7c5b4640ac2897ac17e8c451",
 "version": "0.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
