#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['wright_plans']

package_data = \
{'': ['*']}

install_requires = \
['bluesky', 'pint', 'toolz']

extras_require = \
{'attune': ['attune', 'numpy', 'cycler']}

setup(name='wright_plans',
      version='2021.9.0',
      description='Bluesky plans and utilities to provide functionality that the Wright Group needs.',
      author='Kyle Sunden',
      author_email='contact@ksunden.space',
      url='https://github.com/wright-group/bluesky-wright',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
     )
