
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-07T12:30:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1084ef54d064705f339a19ca476d2bf13721fd7",
 "version": "0.6.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
