
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-14T09:54:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba6b50bd73943777df4454678ad6582db456ab6f",
 "version": "2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
