# Generated by Django 3.1.7 on 2021-08-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_delete_myadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofession',
            options={'verbose_name': 'User Profession'},
        ),
    ]
