#config for single template
single:
  input_string: "PKdhtXMmr18n2L9K88eMlGn7CcctT9RwKSB1FebW397VI5uG1yhc3uavuaOb9vyJ"
  sf:
    start : 7
    end : 12
    increment : 1
  paylen: 64
  frames:
    start : 10
    end: 100
    increment: no
  impl_head:
    start: True
    end: False
    increment : 1
  has_crc:
    start: False
    end: True
  cr:
    start: 0
    end: 4
    increment: 4
  time_wait:
    start: 200
    end: 1000
    increment: 1

#config for multi_stream template
multi_stream:
  input_string: "PKdhtXMmr18n2L9K88eMlGn7CcctT9RwKSB1FebW397VI5uG1yhc3uavuaOb9vyJ"
  sf:
    start : 11
    end : 11
    increment : 1
  paylen: 64
  frames:
    start : 10
    end: 100
    increment: no
  impl_head:
    start: True
    end: False
    increment : 1
  has_crc:
    start: False
    end: True
  cr:
    start: 0
    end: 4
    increment: 4
  time_wait:
    start: 200
    end: 1000
    increment: 1

#config for frame_detector
frame_detector:
  input_string: "PKdhtXMmr18n2L9K88eMlGn7CcctT9RwKSB1FebW397VI5uG1yhc3uavuaOb9vyJ"
  sf:
    start: 11
    end: 11
    increment : 1
  paylen: 64
  frames:
    start: 1000
    end: 1000
    increment: 1
  impl_head:
    start: True
    end: True
  has_crc:
    start: False
    end: False
  cr:
    start: 4
    end: 4
    increment: 1
  time_wait:
    start: 2000
    end: 2000
    increment: 1
  threshold:
    start: 0.2
    end: 2.0
    increment: .2
  snr:
    start: -23
    end: 10
    increment: 2
  sto:
    start: 1
    end: 1
    increment: 1
  cfo:
    start: 0
    end: 0
    increment: 1
