# coding: utf-8

"""
    Nomad Envoy Utils

    This is the API descriptor for the EC Platform and customs utils. Developed by [Samarkand Global](https://samarkand.global), EC Platform including [Youzan](https://www.youzan.com/) Read the documentation online at [Nomad API Suite](https://api.samarkand.io/). - Install for python with `pip install nomad_envoy_utils_cli` - Install for node with `npm install nomad_envoy_utils_cli`  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import nomad_envoy_utils_cli
from nomad_envoy_utils_cli.models.cypher import Cypher  # noqa: E501
from nomad_envoy_utils_cli.rest import ApiException

class TestCypher(unittest.TestCase):
    """Cypher unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Cypher
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = nomad_envoy_utils_cli.models.cypher.Cypher()  # noqa: E501
        if include_optional :
            return Cypher(
                store_id = 'samarkand.youzan.kuiseng', 
                operation = 'DecryptBatch', 
                items = ["test"]
            )
        else :
            return Cypher(
                store_id = 'samarkand.youzan.kuiseng',
                operation = 'DecryptBatch',
        )

    def testCypher(self):
        """Test Cypher"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
