[tool.poetry]
name = "xmp"
version = "0.0.1"
description = "xmp is execute Python code in Markdown code block."
authors = ["hashzmr <rhashizume7729@gmail.com>"]
license = "MIT"
repository = "https://github.com/hashzmr/xmp"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
isort = "^5.9.3"
pytest = "^6.2.5"
pytest-datadir = "^1.3.1"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
xmp = "xmp.main:main"
