#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['django_json_logging']

package_data = \
{'': ['*']}

install_requires = \
['django>=2.2', 'json-log-formatter>=0.3.1, <=0.4.0']

setup(name='django_json_logging',
      version='0.0.6',
      description='Various JSON logging extensions for the Django Framework',
      author='Vicheslav Krachkov',
      author_email='vskrachkov@gmail.com',
      url='https://github.com/vskrachkov/django_json_logging',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.8',
     )
