
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-11T06:52:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "24e9641f8e0e669d7dbecf6f2c8ffae6f6ed75ab",
 "version": "2021.9.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
