
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-10T16:30:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4adc59b830ef6887e726348a3cfab670364e54d7",
 "version": "2021.09.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
