# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {
    "add_spaces": "Client.ipynb",
    "num_spaces": "Client.ipynb",
    "add_last_cell_as_example_in_docstring": "Client.ipynb",
    "check_for_valid_status_codes": "Client.ipynb",
    "post_data": "Client.ipynb",
    "get_data": "Client.ipynb",
    "StatusBase": "Client.ipynb",
    "DataConnectStatus": "Client.ipynb",
    "Client": "Client.ipynb",
    "DataSource": "Client.ipynb",
    "DataSource.pull": "Client.ipynb",
    "DataSource.head": "Client.ipynb",
    "Model": "Client.ipynb",
    "Prediction": "Client.ipynb",
    "Client.train": "Client.ipynb",
    "Model.evaluate": "Client.ipynb",
    "Model.predict": "Client.ipynb",
    "Prediction.to_pandas": "Client.ipynb",
    "Prediction.push": "Client.ipynb",
}

modules = ["client.py"]

doc_url = "//"

git_url = "https://gitlab.com/airt.ai/airt-client/tree/main/"


def custom_doc_links(name):
    return None
