language: python


before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

python:
  - "3.6"

install:
- pip install ".[test]" . # install package + test dependencies

script:
  - pytest
