
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-12T02:14:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a08df9e67b8bd0ba558e03c104b805e2d5a6750f",
 "version": "0.7.dev2137"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
