
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-14T15:58:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d017107422eaccb41e768fd7945485b0327a0eb7",
 "version": "2.4.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
