
scheduler:
  # Scheduler options
  restarting: 'relaunch'

parameters:
  # Add you parameters here that are passed to 
  # tasks that requires such
  env: 'dev'

tasks:
  # Put your meta tasks here
  - class: YAMLLoader
    path: 'tasks/'
    on_startup: True

logging:
  clear_existing: True
  version: 1
  disable_existing_loggers: True

  formatters:
    standard:
      format: '%(asctime)s %(levelname)s %(name)s %(message)s'

    csv_task_formatter:
      (): redengine.log.CsvFormatter
      fields: [
        task_name,
        asctime,
        action,
        start, # Start of the task
        end, # End of the task ('run' does not have end)
        runtime,
        message
      ]

  handlers:
    default:
       level: 'DEBUG'
       formatter: 'standard'
       class: 'logging.StreamHandler'
       stream: 'ext://sys.stdout'
    stderr:
       level: 'ERROR'
       formatter: 'standard'
       class: 'logging.StreamHandler'
       stream: 'ext://sys.stdout'
    csv_task:
       (): "redengine.log.CsvHandler"
       formatter: "csv_task_formatter"
       filename: "tasks.csv"
       make_dir: True
       delay: True

  loggers:
    '': # root logger
       handlers: ['default']
       level: 'WARNING'
       propagate: False
    redengine.task:
       handlers: ['csv_task', 'default']
       level: 'INFO'
       propagate: False
    redengine.scheduler:
       handlers: ['default']
       level: 'INFO'
       propagate: False
    __main__:
       handlers: ['default']
       level: 'DEBUG'
       propagate: False