clients:
  google-chrome-beta: chrome
  jetbrains-(.*):
    icon: terminal
    extra: "{0}"
  firefox: firefox
  x-terminal-emulator: terminal
  thunderbird: envelope
  nautilus: folder-open
  clementine: music
  vlc: play
  signal: comment
deliminator: " "
default_icon: dot-circle
