#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['cantoogf']

package_data = \
{'': ['*']}

setup(name='cantoogf',
      version='1.0.5',
      description='An amazing sample package!',
      author=None,
      author_email='Laika Dog <laika@woof.com>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
