
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f31194f75365787f3eb5da61a24f2f8620111f4f",
 "version": "1.7.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
