name: pygeoogc-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - nest-asyncio
  - ujson

  # pygeoogc deps
  - defusedxml
  - owslib
  - pydantic
  - pyyaml
  - pyproj
  - requests
  - requests-cache>=0.8
  - shapely
  - simplejson
  - urllib3

  # test deps
  - pytest
  - pytest-clarity
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - psutil
  - toml

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
