
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T01:45:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "968fc746a3555ab7d0acf1f47259c5384824cadc",
 "version": "2.4.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
