[tool.poetry]
name = "fastapi_datatables"
version = "0.6.2"
description = "A library, that makes using SQLAlchemy tables with FastAPI easy. It implements filtration, pagination, ordering and text search out of the box. With utilization of FastAPI's \"Depends\" makes it easy to get filtration data from query parameters."
authors = ["LeaveMyYard <zhukovpavel2001@gmail.com>"]
license = "MIT"
packages = [
    { include = "fastapi_datatables" },
]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.68.0"
SQLAlchemy = "1.3.23"
sqlalchemy-filters = "^0.12.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
mypy = "^0.910"
types-requests = "^2.25.6"
fastapi-utils = "^0.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
