name: Static Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 condor_git_config.py tests
    - name: Format with black
      run: |
        black condor_git_config.py tests --diff --check
    - name: Check with mypy
      run: |
        python -m mypy condor_git_config.py
