[tool.poetry]
name = "down-notifier"
version = "0.1.1"
description = "Send notification when your website is down."
authors = ["pegov"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pegov/down-notifier"
repository = "https://github.com/pegov/down-notifier"

[tool.poetry.dependencies]
python = ">=3.7, <4.0"
aiogram = ">=2.14.3"
aiohttp = ">=3.7.4"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
autoflake = "^1.4"
isort = "^5.9.3"
black = "^21.8b0"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
