"""
    Nuaudit

    Managed Audit Trail for Cloud Applications  # noqa: E501

    The version of the OpenAPI document: 0.8.0
    Contact: support@nuaudit.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nuaudit_python_autogen
from nuaudit_python_autogen.model.identity_record import IdentityRecord
from nuaudit_python_autogen.model.resource_record import ResourceRecord
globals()['IdentityRecord'] = IdentityRecord
globals()['ResourceRecord'] = ResourceRecord
from nuaudit_python_autogen.model.record import Record


class TestRecord(unittest.TestCase):
    """Record unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecord(self):
        """Test Record"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Record()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
