"""
    Nuaudit

    Managed Audit Trail for Cloud Applications  # noqa: E501

    The version of the OpenAPI document: 0.8.0
    Contact: support@nuaudit.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import nuaudit_python_autogen
from nuaudit_python_autogen.api.identities_api import IdentitiesApi  # noqa: E501


class TestIdentitiesApi(unittest.TestCase):
    """IdentitiesApi unit test stubs"""

    def setUp(self):
        self.api = IdentitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_identity(self):
        """Test case for get_identity

        Get Identity  # noqa: E501
        """
        pass

    def test_list_identities(self):
        """Test case for list_identities

        List Identities  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
