# coding: utf-8

"""
    Nomad Envoy Utils

    This is the API descriptor for the EC Platform and customs utils. Developed by [Samarkand Global](https://samarkand.global), EC Platform including [Youzan](https://www.youzan.com/) Read the documentation online at [Nomad API Suite](https://api.samarkand.io/). - Install for python with `pip install nomad_envoy_utils_cli` - Install for node with `npm install nomad_envoy_utils_cli`  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import nomad_envoy_utils_cli
from nomad_envoy_utils_cli.api.platform_api import PlatformApi  # noqa: E501
from nomad_envoy_utils_cli.rest import ApiException


class TestPlatformApi(unittest.TestCase):
    """PlatformApi unit test stubs"""

    def setUp(self):
        self.api = nomad_envoy_utils_cli.api.platform_api.PlatformApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_batch_operate_cypher(self):
        """Test case for batch_operate_cypher

        cypher  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
