[tool.poetry]
name = "sphinx-argparse"
version = "0.3.1"
description = "A sphinx extension that automatically documents argparse commands and options"
authors = ["Ash Berlin-Taylor <ash_github@firemirror.com>"]
license = "MIT"
packages = [
  { include = "sphinxarg" },
  { include = "test", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*"
sphinx = ">=1.2.0"
CommonMark = { version = ">=0.5.6", optional = true }

[tool.poetry.extras]
markdown = ["CommonMark"]

[tool.poetry.dev-dependencies]
six = "*"
flake8 = "*"
pytest = "*"
pytest-deadfixtures = "*"
flake8-colors = "^0.1.9"
black = {version = "^20.8b1", allow-prereleases = true, python = ">=3.6h"}
isort = {version = "^5.8.0", python = "^3.6"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
