from setuptools import setup, find_packages

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(name='seebotesttrix',
      version='0.0.2',
      description='Qualitest package automation infrastructure kit tools for GUI and API tests',
      url='https://upload.pypi.org/legacy/',
      author='Yossi Arar & Moshe Sar Idan',
      long_description=long_description,
      long_description_content_type="text/markdown",
      license='MIT',
      packages=find_packages(),
      include_package_data=True,
      zip_safe=False,
      use_scm_version=True,
      classifiers=[
          "Programming Language :: Python :: 3",
          "License :: OSI Approved :: MIT License",
          "Operating System :: OS Independent",
      ],
      install_requires=[
          'allure-pytest==2.9.43',
          'allure-python-commons==2.9.43',
          'appdirs==1.4.4',
          'atomicwrites==1.4.0',
          'attrs==21.2.0',
          'build==0.5.1',
          'certifi==2021.5.30',
          'cffi==1.14.6',
          'chardet==4.0.0',
          'colorama==0.4.4',
          'cryptography==3.4.7',
          'dnspython==1.16.0',
          'idna==2.10',
          'importlib-metadata==4.6.1',
          'iniconfig==1.1.1',
          'isodate==0.6.0',
          'lxml==4.6.3',
          'msal==1.9.0',
          'msal-extensions==0.3.0',
          'msrest==0.6.21',
          'numpy==1.21.0',
          'oauthlib==3.1.1',
          'packaging==21.0',
          'pandas==1.3.0',
          'pep517==0.10.0',
          'pluggy==0.13.1',
          'portalocker==1.7.1',
          'py==1.10.0',
          'pycparser==2.20',
          'PyJWT==2.1.0',
          'pyparsing==2.4.7',
          'python-dateutil==2.8.1',
          'python-snappy==0.6.0',
          'pytz==2021.1',
          'requests==2.25.1',
          'requests-oauthlib==1.3.0',
          'selenium==3.141.0',
          'six==1.16.0',
          'soupsieve==2.2.1',
          'toml==0.10.2',
          'tqdm==4.61.2',
          'typing-extensions==3.10.0.0',
          'urllib3==1.26.6',
          'webdrivermanager==0.10.0',
          'zipp==3.5.0'],
      python_requires='>=3.7',
      )
