[tool.poetry]
name = "proxy-validator"
version = "0.2.5"
description = "Utility for proxy validation"
authors = ["nash <nash@fixmost.com>"]

[tool.poetry.dependencies]
python = ">3.6"
requests = ">=2.24.0"
PySocks = "^1.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
