name: ps_test_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - progressbar2
  - pathos>=0.2
  - numpy
  - spatialist>=0.8
  - pyyaml
  - requests
  - psycopg2
  - sqlalchemy<1.4
  - sqlalchemy-utils
  - geoalchemy2
  - coveralls
  - coverage
  - pytest
  - sphinx
  - sphinxcontrib-bibtex
  - pip
