[tool.poetry]
name = "cyclonedx-python-lib"
version = "0.0.9"
description = "A library for producing CycloneDX SBOM (Software Bill of Materials) files."
authors = ["Paul Horton <phorton@sonatype.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/CycloneDX/cyclonedx-python-lib"
repository = "https://github.com/CycloneDX/cyclonedx-python-lib"
packages = [
    { include = "cyclonedx" }
]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
python = "^3.6"
packageurl-python = "^0.9.4"
requirements_parser = "^0.2.0"
setuptools = "^50.3.2"
importlib-metadata = "^4.8.1"

[tool.poetry.dev-dependencies]
tox = "^3.24.3"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"
