
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-08T02:36:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6a91dc8f3e11a51de7f5418a119a84d19ad97c7",
 "version": "0.7.1.post.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
