[tool.poetry]
name = "valjoux"
version = "0.0.1"
description = ""
authors = ["hazen <hoyeungw@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"
crostab = ">=0.0.11"
veho = ">=0.0.10"
aryth = ">=0.0.12"

[tool.poetry.dev-dependencies]
pytest = ">=6.0.0"
veho = ">=0.0.10"
crostab = ">=0.0.11"
pyspare = ">=0.0.12"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
