
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-13T08:28:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9e10086dd78ec2382035f9cf459fe9099d29bf7",
 "version": "0.0.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
