# Code generated by TRAC

from __future__ import annotations
import typing as _tp  # noqa
import dataclasses as _dc  # noqa
import enum as _enum  # noqa

from .type import *  # noqa



@_dc.dataclass
class FileDefinition:

    storage: _tp.List[str] = _dc.field(default_factory=list)

    storageInfo: _tp.Dict[str, trac.metadata.Value] = _dc.field(default_factory=list)

    storagePath: str = None

    name: str = None

    extension: str = None

    size: int = None

    mimeType: str = None
