name: async_retriever-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - nest-asyncio
  - ujson
  - setuptools

  - coverage
  - toml
  - pytest
  - pytest-clarity
  - pytest-sugar
  - pytest-xdist
  - psutil
  - markupsafe
  - click
  - click-completion
  - click-default-group
  - colorama
  - commonmark
  - cucumber-tag-expressions=2
  - jinja2
  - pprintpp
  - pygments
  - rich
  - shellingham

  - pip
  - pip:
    - ward
