[tool.poetry]
name = "mandatum"
version = "1.2.0"
description = "A python framework to make beatiful cli applications"
authors = ["Zayed Malick <zayedmalick13@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/ZayedMalick/mandatum"
homepage = "https://github.com/ZayedMalick/mandatum"

[tool.poetry.dependencies]
python = "^3.6"
rich = "^7.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

